namespace msdyncrmWorkflowTools_Tests
{
    /// <summary>
    /// The inputs and outputs of every activity in the published 1.0.61.1, read from its registration: activity class,
    /// property, InArgument or OutArgument, and type. Saved workflows refer to them by these names, so they must not
    /// change (see "Keeping existing workflows working" in CONTRIBUTING.md).
    /// </summary>
    internal static class ReleasedActivityArguments
    {
        public static readonly string[] Version_1_0_61_1 =
        {
            "msdyncrmWorkflowTools.AddRoleToTeam Role InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.AddRoleToTeam Team InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.AddRoleToUser Role InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.AddRoleToUser User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.AddUserToTeam User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.AddUserToTeam Team InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.ApplyRoutingRule IncidentRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.AssociateEntity RelationshipName InArgument System.String",
            "msdyncrmWorkflowTools.AssociateEntity RelationshipEntityName InArgument System.String",
            "msdyncrmWorkflowTools.AssociateEntity RecordURL InArgument System.String",
            "msdyncrmWorkflowTools.CalculateAgregateDate FetchXML InArgument System.String",
            "msdyncrmWorkflowTools.CalculateAgregateDate Value OutArgument System.DateTime",
            "msdyncrmWorkflowTools.CalculateAgregateDate Ok OutArgument System.Boolean",
            "msdyncrmWorkflowTools.CalculatePrice TargetRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.CalculateRollupField FieldName InArgument System.String",
            "msdyncrmWorkflowTools.CalculateRollupField ParentRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.CheckAssociateEntity RelationshipName InArgument System.String",
            "msdyncrmWorkflowTools.CheckAssociateEntity RecordURL InArgument System.String",
            "msdyncrmWorkflowTools.CheckAssociateEntity Result OutArgument System.Boolean",
            "msdyncrmWorkflowTools.CheckUserInRole Role InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.CheckUserInRole User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.CheckUserInRole isUserInRole OutArgument System.Boolean",
            "msdyncrmWorkflowTools.CheckUserInTeam Team InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.CheckUserInTeam User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.CheckUserInTeam isUserInTeam OutArgument System.Boolean",
            "msdyncrmWorkflowTools.Class.AddMarketingListToCampaign MarketingList InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.AddMarketingListToCampaign Campaign InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.AddToMarketingList MarketingList InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.AddToMarketingList account InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.AddToMarketingList contact InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.AddToMarketingList lead InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.CopyMarketingListMembers SourceList InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.CopyMarketingListMembers TargetList InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.CopyToStaticList MarketingList InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.DeleteRecord DeleteUsingRecordURL InArgument System.Boolean",
            "msdyncrmWorkflowTools.Class.DeleteRecord DeleteRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.Class.DeleteRecord EntityTypeName InArgument System.String",
            "msdyncrmWorkflowTools.Class.DeleteRecord EntityGuid InArgument System.String",
            "msdyncrmWorkflowTools.Class.DeleteRecordAuditHistory RecordURL InArgument System.String",
            "msdyncrmWorkflowTools.Class.EmailToTeam Email InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.EmailToTeam Team InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.EntityAttachmentToEmail MainRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.Class.EntityAttachmentToEmail FileName InArgument System.String",
            "msdyncrmWorkflowTools.Class.EntityAttachmentToEmail Email InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.EntityAttachmentToEmail RetrieveActivityMimeAttachment InArgument System.Boolean",
            "msdyncrmWorkflowTools.Class.EntityAttachmentToEmail MostRecent InArgument System.Boolean",
            "msdyncrmWorkflowTools.Class.EntityAttachmentToEmail TopRecords InArgument System.Int32",
            "msdyncrmWorkflowTools.Class.ExecuteWorkflowByID RecordID InArgument System.String",
            "msdyncrmWorkflowTools.Class.ExecuteWorkflowByID Process InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.GetInitiatingUser InitiatingUser OutArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.IsMemberOfMarketingList MarketingList InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.IsMemberOfMarketingList MemberOfMarketingList OutArgument System.Boolean",
            "msdyncrmWorkflowTools.Class.IsMemberOfTeam User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.IsMemberOfTeam Team InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.IsMemberOfTeam Result OutArgument System.Boolean",
            "msdyncrmWorkflowTools.Class.NumericFunctions Number1 InArgument System.Decimal",
            "msdyncrmWorkflowTools.Class.NumericFunctions Number2 InArgument System.Decimal",
            "msdyncrmWorkflowTools.Class.NumericFunctions Add OutArgument System.Decimal",
            "msdyncrmWorkflowTools.Class.NumericFunctions Subtract OutArgument System.Decimal",
            "msdyncrmWorkflowTools.Class.NumericFunctions Multiply OutArgument System.Decimal",
            "msdyncrmWorkflowTools.Class.NumericFunctions Divide OutArgument System.Decimal",
            "msdyncrmWorkflowTools.Class.PickFromQueue SourceQueue InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.PickFromQueue RemoveItems InArgument System.Boolean",
            "msdyncrmWorkflowTools.Class.PickFromQueue Quantity InArgument System.Int32",
            "msdyncrmWorkflowTools.Class.QueueItemCount SourceQueue InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.QueueItemCount CountOnlyUnassigned InArgument System.Boolean",
            "msdyncrmWorkflowTools.Class.QueueItemCount ItemsCount OutArgument System.Int32",
            "msdyncrmWorkflowTools.Class.RemoveFromMarketingList MarketingList InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.RemoveFromMarketingList account InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.RemoveFromMarketingList contact InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.RemoveFromMarketingList lead InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.ResolveCase Incident InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.ResolveCase IncidentResolution InArgument System.String",
            "msdyncrmWorkflowTools.Class.ResolveCase ResolutionDescription InArgument System.String",
            "msdyncrmWorkflowTools.Class.SalesLiteratureToEmail SalesLiterature InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.SalesLiteratureToEmail FileName InArgument System.String",
            "msdyncrmWorkflowTools.Class.SalesLiteratureToEmail Email InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.SendEmail SourceEmail InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.SendEmail Subject OutArgument System.String",
            "msdyncrmWorkflowTools.Class.SendEmailFromTemplateToUsersInRole SecurityRoleLookup InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.SendEmailFromTemplateToUsersInRole EmailTemplateLookup InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.SendEmailToUsersInRole SecurityRoleLookup InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.SendEmailToUsersInRole Email InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.SetProcess ClonningRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.Class.SetProcess Process InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.SetProcessStage ClonningRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.Class.SetProcessStage Process InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.Class.SetProcessStage ProcessStage InArgument System.String",
            "msdyncrmWorkflowTools.CloneChildren SourceRecordUrl InArgument System.String",
            "msdyncrmWorkflowTools.CloneChildren TargetRecordUrl InArgument System.String",
            "msdyncrmWorkflowTools.CloneChildren RelationshipName InArgument System.String",
            "msdyncrmWorkflowTools.CloneChildren NewParentFieldNameToUpdate InArgument System.String",
            "msdyncrmWorkflowTools.CloneChildren OldParentFieldNameToUpdate InArgument System.String",
            "msdyncrmWorkflowTools.CloneChildren Prefix InArgument System.String",
            "msdyncrmWorkflowTools.CloneChildren FieldstoIgnore InArgument System.String",
            "msdyncrmWorkflowTools.CloneRecord ClonningRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.CloneRecord Prefix InArgument System.String",
            "msdyncrmWorkflowTools.CloneRecord FieldstoIgnore InArgument System.String",
            "msdyncrmWorkflowTools.CloneRecord ClonedGuid OutArgument System.String",
            "msdyncrmWorkflowTools.ConcatenateFromQuery FetchXml InArgument System.String",
            "msdyncrmWorkflowTools.ConcatenateFromQuery AttributeName InArgument System.String",
            "msdyncrmWorkflowTools.ConcatenateFromQuery Separator InArgument System.String",
            "msdyncrmWorkflowTools.ConcatenateFromQuery FormatString InArgument System.String",
            "msdyncrmWorkflowTools.ConcatenateFromQuery TopRecordCount InArgument System.Int32",
            "msdyncrmWorkflowTools.ConcatenateFromQuery ConcatenatedString OutArgument System.String",
            "msdyncrmWorkflowTools.CountChildEntityRecords ChildEntityName InArgument System.String",
            "msdyncrmWorkflowTools.CountChildEntityRecords ParentLookupName InArgument System.String",
            "msdyncrmWorkflowTools.CountChildEntityRecords RecordURL InArgument System.String",
            "msdyncrmWorkflowTools.CountChildEntityRecords FilterExpressionXml InArgument System.String",
            "msdyncrmWorkflowTools.CountChildEntityRecords Result OutArgument System.Int32",
            "msdyncrmWorkflowTools.CreateTeam TeamName InArgument System.String",
            "msdyncrmWorkflowTools.CreateTeam TeamType InArgument System.Int32",
            "msdyncrmWorkflowTools.CreateTeam Administrator InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.CreateTeam BusinessUnit InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.CreateTeam createdTeam OutArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.CurrencyConvert Amount InArgument System.Decimal",
            "msdyncrmWorkflowTools.CurrencyConvert FromCurrency InArgument System.String",
            "msdyncrmWorkflowTools.CurrencyConvert ToCurrency InArgument System.String",
            "msdyncrmWorkflowTools.CurrencyConvert Result OutArgument System.Decimal",
            "msdyncrmWorkflowTools.DateFunctions Date1 InArgument System.DateTime",
            "msdyncrmWorkflowTools.DateFunctions Date2 InArgument System.DateTime",
            "msdyncrmWorkflowTools.DateFunctions TotalDays OutArgument System.Double",
            "msdyncrmWorkflowTools.DateFunctions TotalHours OutArgument System.Double",
            "msdyncrmWorkflowTools.DateFunctions TotalMilliseconds OutArgument System.Double",
            "msdyncrmWorkflowTools.DateFunctions TotalMinutes OutArgument System.Double",
            "msdyncrmWorkflowTools.DateFunctions TotalSeconds OutArgument System.Double",
            "msdyncrmWorkflowTools.DateFunctions DayOfWeek OutArgument System.Int32",
            "msdyncrmWorkflowTools.DateFunctions DayOfYear OutArgument System.Int32",
            "msdyncrmWorkflowTools.DateFunctions Day OutArgument System.Int32",
            "msdyncrmWorkflowTools.DateFunctions Month OutArgument System.Int32",
            "msdyncrmWorkflowTools.DateFunctions Year OutArgument System.Int32",
            "msdyncrmWorkflowTools.DateFunctions WeekOfYear OutArgument System.Int32",
            "msdyncrmWorkflowTools.DeleteOptionValue GlobalOptionSet InArgument System.Boolean",
            "msdyncrmWorkflowTools.DeleteOptionValue AttributeName InArgument System.String",
            "msdyncrmWorkflowTools.DeleteOptionValue EntityName InArgument System.String",
            "msdyncrmWorkflowTools.DeleteOptionValue OptionValue InArgument System.Int32",
            "msdyncrmWorkflowTools.DisassociateEntity RelationshipName InArgument System.String",
            "msdyncrmWorkflowTools.DisassociateEntity RecordURL InArgument System.String",
            "msdyncrmWorkflowTools.EncryptText TexttoEncrypt InArgument System.String",
            "msdyncrmWorkflowTools.EncryptText MD5HashValue OutArgument System.String",
            "msdyncrmWorkflowTools.EncryptText SHA512HashValue OutArgument System.String",
            "msdyncrmWorkflowTools.EntityJsonSerializer SerializingRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.EntityJsonSerializer OutputJson OutArgument System.String",
            "msdyncrmWorkflowTools.EntityMobileDeepLink RecordURL InArgument System.String",
            "msdyncrmWorkflowTools.EntityMobileDeepLink MobileDeepLinkEdit OutArgument System.String",
            "msdyncrmWorkflowTools.EntityMobileDeepLink MobileDeepLinkNew OutArgument System.String",
            "msdyncrmWorkflowTools.EntityMobileDeepLink MobileDeepLinkDefaultView OutArgument System.String",
            "msdyncrmWorkflowTools.GeoCodeAddress Address InArgument System.String",
            "msdyncrmWorkflowTools.GeoCodeAddress BingMapsKey InArgument System.String",
            "msdyncrmWorkflowTools.GeoCodeAddress Latitude OutArgument System.Decimal",
            "msdyncrmWorkflowTools.GeoCodeAddress Longitude OutArgument System.Decimal",
            "msdyncrmWorkflowTools.GetAppModuleID AppModuleUniqueName InArgument System.String",
            "msdyncrmWorkflowTools.GetAppModuleID AppModuleId OutArgument System.String",
            "msdyncrmWorkflowTools.GetAppRecordUrl RecordURL InArgument System.String",
            "msdyncrmWorkflowTools.GetAppRecordUrl AppModuleUniqueName InArgument System.String",
            "msdyncrmWorkflowTools.GetAppRecordUrl AppRecordUrl OutArgument System.String",
            "msdyncrmWorkflowTools.GetMultiSelectOptionSet SourceRecordUrl InArgument System.String",
            "msdyncrmWorkflowTools.GetMultiSelectOptionSet AttributeName InArgument System.String",
            "msdyncrmWorkflowTools.GetMultiSelectOptionSet RetrieveOptionsNames InArgument System.Boolean",
            "msdyncrmWorkflowTools.GetMultiSelectOptionSet SelectedValues OutArgument System.String",
            "msdyncrmWorkflowTools.GetMultiSelectOptionSet SelectedNames OutArgument System.String",
            "msdyncrmWorkflowTools.GetOptionSetValue SourceRecordUrl InArgument System.String",
            "msdyncrmWorkflowTools.GetOptionSetValue AttributeName InArgument System.String",
            "msdyncrmWorkflowTools.GetOptionSetValue SelectedValue OutArgument System.Int32",
            "msdyncrmWorkflowTools.GetRecordID RecordURL InArgument System.String",
            "msdyncrmWorkflowTools.GetRecordID RecordID OutArgument System.String",
            "msdyncrmWorkflowTools.GetSharepointLocationURL RecordURL InArgument System.String",
            "msdyncrmWorkflowTools.GetSharepointLocationURL SharepointLocationURL OutArgument System.String",
            "msdyncrmWorkflowTools.GoalRecalculate Goal InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.GoalRecalculate GoalGuid InArgument System.String",
            "msdyncrmWorkflowTools.InsertOptionValue GlobalOptionSet InArgument System.Boolean",
            "msdyncrmWorkflowTools.InsertOptionValue AttributeName InArgument System.String",
            "msdyncrmWorkflowTools.InsertOptionValue EntityName InArgument System.String",
            "msdyncrmWorkflowTools.InsertOptionValue OptionText InArgument System.String",
            "msdyncrmWorkflowTools.InsertOptionValue OptionValue InArgument System.Int32",
            "msdyncrmWorkflowTools.InsertOptionValue LanguageCode InArgument System.Int32",
            "msdyncrmWorkflowTools.JsonParser JSON InArgument System.String",
            "msdyncrmWorkflowTools.JsonParser JSONPath InArgument System.String",
            "msdyncrmWorkflowTools.JsonParser JSONResult OutArgument System.String",
            "msdyncrmWorkflowTools.MapMultiSelectOptionSet SourceRecordUrl InArgument System.String",
            "msdyncrmWorkflowTools.MapMultiSelectOptionSet SourceAttributes InArgument System.String",
            "msdyncrmWorkflowTools.MapMultiSelectOptionSet TargetRecordUrl InArgument System.String",
            "msdyncrmWorkflowTools.MapMultiSelectOptionSet TargetAttributes InArgument System.String",
            "msdyncrmWorkflowTools.MapMultiSelectOptionSet KeepExistingValues InArgument System.Boolean",
            "msdyncrmWorkflowTools.OrgDBSettingsRetrieve orgDBSetting InArgument System.String",
            "msdyncrmWorkflowTools.OrgDBSettingsRetrieve StringValue OutArgument System.String",
            "msdyncrmWorkflowTools.OrgDBSettingsRetrieve NumericValue OutArgument System.Decimal",
            "msdyncrmWorkflowTools.OrgDBSettingsRetrieve BoolValue OutArgument System.Boolean",
            "msdyncrmWorkflowTools.OrgDBSettingsUpdate orgDBSetting InArgument System.String",
            "msdyncrmWorkflowTools.OrgDBSettingsUpdate Value InArgument System.String",
            "msdyncrmWorkflowTools.QualifyLead Lead InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.QualifyLead CreateAccount InArgument System.Boolean",
            "msdyncrmWorkflowTools.QualifyLead CreateContact InArgument System.Boolean",
            "msdyncrmWorkflowTools.QualifyLead CreateOpportunity InArgument System.Boolean",
            "msdyncrmWorkflowTools.QualifyLead ExistingAccount InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.QualifyLead ExistingContact InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.QualifyLead LeadStatus InArgument System.Int32",
            "msdyncrmWorkflowTools.QueryValues EntityName InArgument System.String",
            "msdyncrmWorkflowTools.QueryValues Attribute1 InArgument System.String",
            "msdyncrmWorkflowTools.QueryValues Attribute2 InArgument System.String",
            "msdyncrmWorkflowTools.QueryValues FilterAttribute1 InArgument System.String",
            "msdyncrmWorkflowTools.QueryValues ValueAttribute1 InArgument System.String",
            "msdyncrmWorkflowTools.QueryValues FilterAttribute2 InArgument System.String",
            "msdyncrmWorkflowTools.QueryValues ValueAttribute2 InArgument System.String",
            "msdyncrmWorkflowTools.QueryValues ResultValue1 OutArgument System.String",
            "msdyncrmWorkflowTools.QueryValues ResultValue2 OutArgument System.String",
            "msdyncrmWorkflowTools.RemoveRoleFromTeam Role InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.RemoveRoleFromTeam Team InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.RemoveRoleFromUser Role InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.RemoveRoleFromUser User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.RemoveUserFromTeam User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.RemoveUserFromTeam Team InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.RetrieveUserBUDefaultTeam User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.RetrieveUserBUDefaultTeam DefaultTeam OutArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.RollupFunctions FetchXML InArgument System.String",
            "msdyncrmWorkflowTools.RollupFunctions Count OutArgument System.Decimal",
            "msdyncrmWorkflowTools.RollupFunctions Sum OutArgument System.Decimal",
            "msdyncrmWorkflowTools.RollupFunctions Average OutArgument System.Decimal",
            "msdyncrmWorkflowTools.RollupFunctions Max OutArgument System.Decimal",
            "msdyncrmWorkflowTools.RollupFunctions Min OutArgument System.Decimal",
            "msdyncrmWorkflowTools.SetLookupFieldFromRecordUrl RecordUrl InArgument System.String",
            "msdyncrmWorkflowTools.SetLookupFieldFromRecordUrl LookupFieldName InArgument System.String",
            "msdyncrmWorkflowTools.SetMultiSelectOptionSet TargetRecordUrl InArgument System.String",
            "msdyncrmWorkflowTools.SetMultiSelectOptionSet AttributeName InArgument System.String",
            "msdyncrmWorkflowTools.SetMultiSelectOptionSet AttributeValues InArgument System.String",
            "msdyncrmWorkflowTools.SetMultiSelectOptionSet KeepExistingValues InArgument System.Boolean",
            "msdyncrmWorkflowTools.SetState State InArgument System.Int32",
            "msdyncrmWorkflowTools.SetState Status InArgument System.Int32",
            "msdyncrmWorkflowTools.SetUserSettings User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.SetUserSettings PagingLimit InArgument System.Int32",
            "msdyncrmWorkflowTools.SetUserSettings AdvancedFindStartupMode InArgument System.Int32",
            "msdyncrmWorkflowTools.SetUserSettings TimeZoneCode InArgument System.Int32",
            "msdyncrmWorkflowTools.SetUserSettings HelpLanguageId InArgument System.Int32",
            "msdyncrmWorkflowTools.SetUserSettings UILanguageId InArgument System.Int32",
            "msdyncrmWorkflowTools.SetUserSettings DefaultCalendarView InArgument System.Int32",
            "msdyncrmWorkflowTools.SetUserSettings IsSendAsAllowed InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithTeam SharingRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.ShareRecordWithTeam Team InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.ShareRecordWithTeam ShareRead InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithTeam ShareWrite InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithTeam ShareDelete InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithTeam ShareAppend InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithTeam ShareAppendTo InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithTeam ShareAssign InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithTeam ShareShare InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithUser SharingRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.ShareRecordWithUser User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.ShareRecordWithUser ShareRead InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithUser ShareWrite InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithUser ShareDelete InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithUser ShareAppend InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithUser ShareAppendTo InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithUser ShareAssign InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareRecordWithUser ShareShare InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareSecuredField RecordURL InArgument System.String",
            "msdyncrmWorkflowTools.ShareSecuredField AttributeName InArgument System.String",
            "msdyncrmWorkflowTools.ShareSecuredField UserToShare InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.ShareSecuredField TeamToShare InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.ShareSecuredField AllowRead InArgument System.Boolean",
            "msdyncrmWorkflowTools.ShareSecuredField AllowUpdate InArgument System.Boolean",
            "msdyncrmWorkflowTools.StringFunctions InputText InArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions CapitalizeAllWords InArgument System.Boolean",
            "msdyncrmWorkflowTools.StringFunctions PadCharacter InArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions PadontheLeft InArgument System.Boolean",
            "msdyncrmWorkflowTools.StringFunctions FinalLengthwithPadding InArgument System.Int32",
            "msdyncrmWorkflowTools.StringFunctions ReplaceOldValue InArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions ReplaceNewValue InArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions CaseSensitive InArgument System.Boolean",
            "msdyncrmWorkflowTools.StringFunctions FromLefttoRight InArgument System.Boolean",
            "msdyncrmWorkflowTools.StringFunctions StartIndex InArgument System.Int32",
            "msdyncrmWorkflowTools.StringFunctions SubStringLength InArgument System.Int32",
            "msdyncrmWorkflowTools.StringFunctions RegularExpression InArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions CapitalizedText OutArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions TextLength OutArgument System.Int32",
            "msdyncrmWorkflowTools.StringFunctions PaddedText OutArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions ReplacedText OutArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions SubstringText OutArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions TrimmedText OutArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions RegexSuccess OutArgument System.Boolean",
            "msdyncrmWorkflowTools.StringFunctions RegexText OutArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions UppercaseText OutArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions LowercaseText OutArgument System.String",
            "msdyncrmWorkflowTools.StringFunctions WithoutSpaces OutArgument System.String",
            "msdyncrmWorkflowTools.TranslateText TextToTranslate InArgument System.String",
            "msdyncrmWorkflowTools.TranslateText Language InArgument System.String",
            "msdyncrmWorkflowTools.TranslateText Authenticationkey InArgument System.String",
            "msdyncrmWorkflowTools.TranslateText TranslatedText OutArgument System.String",
            "msdyncrmWorkflowTools.UnshareRecordWithTeam SharingRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.UnshareRecordWithTeam Team InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.UnshareRecordWithUser SharingRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.UnshareRecordWithUser User InArgument Microsoft.Xrm.Sdk.EntityReference",
            "msdyncrmWorkflowTools.UpdateChildRecords ParentRecordURL InArgument System.String",
            "msdyncrmWorkflowTools.UpdateChildRecords RelationshipName InArgument System.String",
            "msdyncrmWorkflowTools.UpdateChildRecords ParentFieldNameToUpdate InArgument System.String",
            "msdyncrmWorkflowTools.UpdateChildRecords ValueToSet InArgument System.String",
            "msdyncrmWorkflowTools.UpdateChildRecords ChildFieldNameToUpdate InArgument System.String",
            "msdyncrmWorkflowTools.UpdateChildRecords UpdateonlyActive InArgument System.Boolean"
        };

        /// <summary>
        /// The activities upstream's powerplatformWorkflowTools project (1.0.61.1 source) builds. Their arguments are the ones
        /// above, so the Power Platform build must keep them too.
        /// </summary>
        public static readonly string[] PowerPlatform_1_0_61_1 =
        {
            "msdyncrmWorkflowTools.AddRoleToTeam",
            "msdyncrmWorkflowTools.AddRoleToUser",
            "msdyncrmWorkflowTools.AddUserToTeam",
            "msdyncrmWorkflowTools.ApplyRoutingRule",
            "msdyncrmWorkflowTools.AssociateEntity",
            "msdyncrmWorkflowTools.CalculateAgregateDate",
            "msdyncrmWorkflowTools.CalculatePrice",
            "msdyncrmWorkflowTools.CalculateRollupField",
            "msdyncrmWorkflowTools.CheckAssociateEntity",
            "msdyncrmWorkflowTools.CheckUserInRole",
            "msdyncrmWorkflowTools.CheckUserInTeam",
            "msdyncrmWorkflowTools.Class.DeleteRecord",
            "msdyncrmWorkflowTools.Class.DeleteRecordAuditHistory",
            "msdyncrmWorkflowTools.Class.EmailToTeam",
            "msdyncrmWorkflowTools.Class.EntityAttachmentToEmail",
            "msdyncrmWorkflowTools.Class.ExecuteWorkflowByID",
            "msdyncrmWorkflowTools.Class.GetInitiatingUser",
            "msdyncrmWorkflowTools.Class.IsMemberOfTeam",
            "msdyncrmWorkflowTools.Class.NumericFunctions",
            "msdyncrmWorkflowTools.Class.PickFromQueue",
            "msdyncrmWorkflowTools.Class.QueueItemCount",
            "msdyncrmWorkflowTools.Class.SendEmail",
            "msdyncrmWorkflowTools.Class.SendEmailFromTemplateToUsersInRole",
            "msdyncrmWorkflowTools.Class.SendEmailToUsersInRole",
            "msdyncrmWorkflowTools.Class.SetProcess",
            "msdyncrmWorkflowTools.Class.SetProcessStage",
            "msdyncrmWorkflowTools.CloneChildren",
            "msdyncrmWorkflowTools.CloneRecord",
            "msdyncrmWorkflowTools.ConcatenateFromQuery",
            "msdyncrmWorkflowTools.CountChildEntityRecords",
            "msdyncrmWorkflowTools.CreateTeam",
            "msdyncrmWorkflowTools.CurrencyConvert",
            "msdyncrmWorkflowTools.DateFunctions",
            "msdyncrmWorkflowTools.DeleteOptionValue",
            "msdyncrmWorkflowTools.DisassociateEntity",
            "msdyncrmWorkflowTools.EncryptText",
            "msdyncrmWorkflowTools.EntityJsonSerializer",
            "msdyncrmWorkflowTools.EntityMobileDeepLink",
            "msdyncrmWorkflowTools.GeoCodeAddress",
            "msdyncrmWorkflowTools.GetAppModuleID",
            "msdyncrmWorkflowTools.GetAppRecordUrl",
            "msdyncrmWorkflowTools.GetMultiSelectOptionSet",
            "msdyncrmWorkflowTools.GetOptionSetValue",
            "msdyncrmWorkflowTools.GetRecordID",
            "msdyncrmWorkflowTools.GetSharepointLocationURL",
            "msdyncrmWorkflowTools.GoalRecalculate",
            "msdyncrmWorkflowTools.InsertOptionValue",
            "msdyncrmWorkflowTools.JsonParser",
            "msdyncrmWorkflowTools.MapMultiSelectOptionSet",
            "msdyncrmWorkflowTools.OrgDBSettingsRetrieve",
            "msdyncrmWorkflowTools.OrgDBSettingsUpdate",
            "msdyncrmWorkflowTools.QueryValues",
            "msdyncrmWorkflowTools.RemoveRoleFromTeam",
            "msdyncrmWorkflowTools.RemoveRoleFromUser",
            "msdyncrmWorkflowTools.RemoveUserFromTeam",
            "msdyncrmWorkflowTools.RetrieveUserBUDefaultTeam",
            "msdyncrmWorkflowTools.RollupFunctions",
            "msdyncrmWorkflowTools.SetLookupFieldFromRecordUrl",
            "msdyncrmWorkflowTools.SetMultiSelectOptionSet",
            "msdyncrmWorkflowTools.SetState",
            "msdyncrmWorkflowTools.SetUserSettings",
            "msdyncrmWorkflowTools.ShareRecordWithTeam",
            "msdyncrmWorkflowTools.ShareRecordWithUser",
            "msdyncrmWorkflowTools.ShareSecuredField",
            "msdyncrmWorkflowTools.StringFunctions",
            "msdyncrmWorkflowTools.TranslateText",
            "msdyncrmWorkflowTools.UnshareRecordWithTeam",
            "msdyncrmWorkflowTools.UnshareRecordWithUser",
            "msdyncrmWorkflowTools.UpdateChildRecords"
        };
    }
}
